[package]
name = "ifengine"
version = "0.0.6"
authors = ["Squirreljetpack"]
edition = "2024"
include = ["LICENSE-APACHE", "LICENSE-MIT", "**/*.rs", "Cargo.toml"]
description = "Interactive fiction library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Squirreljetpack/ifengine"
readme = "README.md"
keywords = ["engine", "game", "macro", "rust"]
categories = ["development-tools", "game-development"] #  "game‑engines", not accepted

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true

[dependencies]
ifengine_core = { version = "0.0.6", path = "../ifengine_core" }
ifengine_macros = { version = "0.*", path = "../ifengine_macros", optional = true }

[features]
default = ["macros"]
macros = ["dep:ifengine_macros"]
serde = ["ifengine_core/serde"]
rand = ["ifengine_core/rand"]
utils = ["ifengine_core/utils"]

